version: '3.8'
services:
  frontend:
    build: './frontend'
    container_name: Gomobile_frontend
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

      
  backend:
    build: './backend'
    container_name: Gomobile_backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/backend
